### ISSUE TITLE
cannot get UserID from Twitch API

### ISSUE THREAD

**Issue by Baxxster** [StinkingBanana/tut#2]
Hello,

I installed this, created an app, copied the ClientID
I went to the OAuth generator, copied the entire string
I chose the twitch name to track, but the response I get is:

2019/11/07 15:42:14 getUserIDFromTwitch: cannot get UserID from Twitch API, check your ClientID or username

Any fix for this?

**Comment by wei0831** [comment]
sorry for the very late reply
I will find time to fix this...

**Comment by wei0831** [comment]
Sorry for the late reply.

For a quick dirty fix, 

- Get the latest release.
- Instead of using twitch tmi to generate OAuth token,

   - Obtain your Access Token using the following URL

   ```
     https://id.twitch.tv/oauth2/authorize?response_type=token&client_id={ClientID}&redirect_uri=http://localhost&scope=viewing_activity_read
   ```

   - Replace {ClientID} with your ClientID and enter in your browser.
   - Authorzie it.
   - If nothing goes wrong, you should get an empty white page with URL similar to http://localhost/#access_token={AccessToken}&...
   - Extract that {AccessToken} and paste into our tut program
   - Note: the access token will expire after sometime. If the access token no longer works, generate a new one using the same method.
   
If I have more time in the future, I will make it auto-authorize itself...
